export const IPC_CHANNELS = {
  FS_READ_DIRECTORY: "fs:read-directory",
  FS_GET_SYSTEM_DIRECTORIES: "fs:get-system-directories",
  FS_GET_EXTERNAL_VOLUMES: "fs:get-external-volumes",
  FAVORITES_LIST: "favorites:list",
  FAVORITES_ADD: "favorites:add",
  FAVORITES_REMOVE: "favorites:remove",
  FAVORITES_SET_RATING: "favorites:set-rating",
  FAVORITES_GET_RATING: "favorites:get-rating",
  FAVORITES_LIST_BY_RATING: "favorites:list-by-rating",
  FILEOPS_DELETE: "fileops:delete",
  FILEOPS_REVEAL: "fileops:reveal",
  FILEOPS_RENAME: "fileops:rename",
  FILEOPS_EXPORT: "fileops:export",
  FILEOPS_MOVE: "fileops:move",
  FILEOPS_COPY: "fileops:copy",
  FS_WATCH_DIRECTORY: "fs:watch-directory",
  FS_UNWATCH_DIRECTORY: "fs:unwatch-directory",
  FS_DIRECTORY_CHANGED: "fs:directory-changed",
  THEME_GET: "theme:get",
  THEME_UPDATED: "theme:updated",
  PREFERENCES_GET: "preferences:get",
  PREFERENCES_SET: "preferences:set",
  APP_ACTION: "app:action",
  PSD_GET_GROUPS: "psd:get-groups",
  PSD_GET_METADATA: "psd:get-metadata",
  PSD_SET_EDITED: "psd:set-edited",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
